version: "3"
services:
  inventory-service:
    build: .
    container_name: inventory-service
    ports:
      - "8001:8001"
    expose:
      - "8001"

    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "8002:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: [ "start-dev" ]


  dashboard-frontend:
    build: ../dashboard/
    container_name: inventory-ui
    ports:
      - '4200:80'
    expose:
      - '4200'


